language: ruby
rvm:
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler
script:
  - bundle exec rake test
after_success:
  - bundle exec codeclimate-test-reporter
